In [1]:
import numpy as np

In [4]:
mat = np.arange(0,100).reshape(10,10)
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [7]:
# index based selection
mat[8,7]

87

In [9]:
# slicing :  choose a column
mat[:, 2] # column 3

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [13]:
# slicing : choose a row
rowslice = mat[3, :] # row 4
rowslice

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [14]:
# reshape a chosen row
rowslice.reshape(5,2)

array([[30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [15]:
# slicing : sub set of rows and colums
mat[0:3, 0:3] # slice first 3 rows and columns

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [27]:
# re assign the values of the chosen subset of rows and columns
mat[0:3, 0:3] =9009
mat

array([[9009, 9009, 9009,    3,    4,    5,    6,    7,    8,    9],
       [9009, 9009, 9009,   13,   14,   15,   16,   17,   18,   19],
       [9009, 9009, 9009,   23,   24,   25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34,   35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

In [31]:
# Color channels, RGB, as a 3D array (H, W, Colours)
pic = np.arange(0,120).reshape(10, 4, 3) # len of range must always be >= product of the dimensions
pic

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11]],

       [[ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23]],

       [[ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35]],

       [[ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44],
        [ 45,  46,  47]],

       [[ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59]],

       [[ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71]],

       [[ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83]],

       [[ 84,  85,  86],
        [ 87,  88,  89],
        [ 90,  91,  92],
        [ 93,  94,  95]],

       [[ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107]],

       [[108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
       